import { createSignal, For, Show } from "solid-js";
import { save } from "@tauri-apps/plugin-dialog";
import { invoke } from "@tauri-apps/api/core";
import type { Manifest } from "../types/manifest";
import type { ChatMessage, GeneratedPlan, ReadingLevel } from "../types/onboarding";

const READY_SIGNAL = "Ready to generate your lesson plan.";

const READING_LEVELS: { id: ReadingLevel; label: string; sublabel: string; sample: string }[] = [
  {
    id: "child",
    label: "Child",
    sublabel: "Ages 8–12",
    sample:
      "Butterfly wings are covered in tiny scales, like a mosaic of very small tiles. Some scales hold color the way crayons do — it's baked right in. But other butterflies, like the bright blue Morpho butterfly, make their color a different way. Their scales have ridges so small you can't see them, and when light bounces off those ridges, only the blue part comes back to your eyes. It's the same reason soap bubbles look rainbow-colored. The wings aren't actually blue — they're playing a trick with light.",
  },
  {
    id: "teen",
    label: "Teen",
    sublabel: "Ages 13–17",
    sample:
      "Butterfly wings get their color from two very different sources. The first is pigment — chemical compounds in the wing scales that absorb some wavelengths of light and reflect others, the same basic mechanism behind any paint or dye. The second is structural color, which is more unusual. Some species, particularly the Morpho butterflies of South America, have wing scales built with microscopic layered ridges that interfere with light waves. The layers are spaced so that certain wavelengths amplify each other while others cancel out, producing an intense iridescence that shifts depending on your viewing angle — and contains no pigment at all.",
  },
  {
    id: "adult",
    label: "Adult",
    sublabel: "General reading",
    sample:
      "A butterfly's wing color can arise from two distinct physical mechanisms, and many species exploit both simultaneously. Pigment-based color — produced by compounds like melanins and flavonoids embedded in the wing scales — works through selective light absorption, reflecting only the wavelengths we perceive as a given hue. Structural color operates differently: microscopic architectures within the scale generate color through optical interference rather than chemistry. The Morpho genus is the canonical example, its electric blue produced entirely by nanostructured ridges that selectively amplify blue wavelengths and suppress others. Because structural color depends on geometry, it shifts as the wing moves — a property that has drawn significant interest in materials science, where engineers are working to replicate it for displays and anti-counterfeiting.",
  },
  {
    id: "academic",
    label: "Academic",
    sublabel: "Professional / postgraduate",
    sample:
      "Wing coloration in Lepidoptera arises through two non-exclusive mechanisms: pigmentary absorption and coherent light scattering. Pigment-based coloration is mediated by chromophores — principally melanins, ommochromes, and sequestered dietary flavonoids — embedded within chitinous scale lamellae, with perceived hue determined by the spectral distribution of reflected radiation following wavelength-selective absorption. Structural coloration is generated by periodic nanoarchitectures within the scale ultrastructure; in the Morpho clade, multilayer thin-film interference arising from quasi-ordered arrays of cuticle ridges produces high-reflectance peaks in the 430–500 nm range. The ecological functions of these coloration systems — aposematism, crypsis, intraspecific signaling, thermoregulation — are diverse, and the selection pressures maintaining structural versus pigmentary strategies remain an active area of inquiry.",
  },
];

interface Props {
  topic: string;
  onBook: (manifest: Manifest) => void;
  onBack: () => void;
}

export default function OnboardingView(props: Props) {
  const [readingLevel, setReadingLevel] = createSignal<ReadingLevel | null>(null);
  const [messages, setMessages] = createSignal<ChatMessage[]>([]);
  const [input, setInput] = createSignal("");
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");
  const [plan, setPlan] = createSignal<GeneratedPlan | null>(null);
  const [saving, setSaving] = createSignal(false);

  const lastAssistantMessage = () => {
    const msgs = messages();
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "assistant") return msgs[i].content;
    }
    return "";
  };

  const llmSignaledReady = () => lastAssistantMessage().includes(READY_SIGNAL);
  const canGeneratePlan = () => messages().some((m) => m.role === "assistant") && !loading();

  async function handleLevelSelect(level: ReadingLevel) {
    setReadingLevel(level);
    setLoading(true);
    setError("");
    try {
      const response = await invoke<string>("begin_onboarding", { topic: props.topic, readingLevel: level });
      setMessages([{ role: "assistant", content: response }]);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  async function sendMessage() {
    const text = input().trim();
    if (!text || loading()) return;
    setInput("");
    setError("");

    const updated: ChatMessage[] = [...messages(), { role: "user", content: text }];
    setMessages(updated);
    setLoading(true);

    try {
      const response = await invoke<string>("continue_onboarding", {
        topic: props.topic,
        readingLevel: readingLevel(),
        conversation: updated,
      });
      setMessages([...updated, { role: "assistant", content: response }]);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  async function handleGeneratePlan() {
    setLoading(true);
    setError("");
    try {
      const generated = await invoke<GeneratedPlan>("generate_lesson_plan", {
        topic: props.topic,
        readingLevel: readingLevel(),
        conversation: messages(),
      });
      setPlan(generated);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  async function handleSaveBook() {
    const currentPlan = plan();
    if (!currentPlan) return;
    setError("");

    const dialogPath = await save({
      title: "Save Book",
      filters: [{ name: "Scholium Book", extensions: ["scholium"] }],
    });
    if (!dialogPath) return;

    setSaving(true);
    try {
      const manifest = await invoke<Manifest>("create_book", {
        topic: props.topic,
        dialogPath,
        plan: currentPlan,
        readingLevel: readingLevel()!,
      });
      props.onBook(manifest);
    } catch (e) {
      setError(String(e));
      setSaving(false);
    }
  }

  return (
    <div class="onboarding-shell">
      <header class="onboarding-header">
        <button class="btn-back" onClick={props.onBack} disabled={loading() || saving()}>
          ← Back
        </button>
        <div class="onboarding-topic">
          <span class="onboarding-topic-label">Topic:</span>
          <span class="onboarding-topic-value">{props.topic}</span>
        </div>
      </header>

      <Show when={readingLevel() !== null} fallback={<ReadingLevelSelector onSelect={handleLevelSelect} />}>
        <Show when={!plan()} fallback={<PlanPreview plan={plan()!} onSave={handleSaveBook} saving={saving()} />}>
          <div class="chat-area">
            <div class="chat-messages" id="chat-messages">
              <Show when={messages().length === 0 && loading()}>
                <div class="chat-loading">Starting conversation…</div>
              </Show>
              <For each={messages()}>
                {(msg) => (
                  <div class={`chat-bubble chat-bubble--${msg.role}`}>
                    <p>{msg.content}</p>
                  </div>
                )}
              </For>
              <Show when={loading() && messages().length > 0}>
                <div class="chat-bubble chat-bubble--assistant chat-bubble--thinking">
                  <span class="thinking-dot" /><span class="thinking-dot" /><span class="thinking-dot" />
                </div>
              </Show>
            </div>

            {error() && <p class="field-error" role="alert">{error()}</p>}

            <div class="chat-input-row">
              <textarea
                class="chat-input"
                rows={2}
                placeholder="Type your response…"
                value={input()}
                onInput={(e) => setInput(e.currentTarget.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void sendMessage(); }
                }}
                disabled={loading() || messages().length === 0}
              />
              <button
                class="btn-send"
                onClick={sendMessage}
                disabled={input().trim().length === 0 || loading() || messages().length === 0}
              >
                Send
              </button>
            </div>

            <div class="chat-actions">
              <button
                class="btn-primary"
                disabled={!canGeneratePlan()}
                onClick={handleGeneratePlan}
              >
                {llmSignaledReady() ? "Generate Lesson Plan ✓" : "Generate Lesson Plan"}
              </button>
            </div>
          </div>
        </Show>
      </Show>
    </div>
  );
}

function ReadingLevelSelector(props: { onSelect: (level: ReadingLevel) => void }) {
  const [selected, setSelected] = createSignal<ReadingLevel | null>(null);

  return (
    <div class="reading-level-selector">
      <div class="reading-level-header">
        <h2>How do you prefer to read?</h2>
        <p>Choose the sample that feels most natural.</p>
      </div>
      <div class="reading-level-cards">
        <For each={READING_LEVELS}>
          {(level) => (
            <button
              class={`reading-level-card${selected() === level.id ? " reading-level-card--selected" : ""}`}
              onClick={() => setSelected(level.id)}
            >
              <div class="reading-level-card-header">
                <strong class="reading-level-label">{level.label}</strong>
                <span class="reading-level-sublabel">{level.sublabel}</span>
              </div>
              <p class="reading-level-sample">{level.sample}</p>
            </button>
          )}
        </For>
      </div>
      <div class="reading-level-actions">
        <button
          class="btn-primary"
          disabled={selected() === null}
          onClick={() => props.onSelect(selected()!)}
        >
          Continue
        </button>
      </div>
    </div>
  );
}

interface PlanPreviewProps {
  plan: GeneratedPlan;
  onSave: () => void;
  saving: boolean;
}

function PlanPreview(props: PlanPreviewProps) {
  return (
    <div class="plan-preview">
      <h2 class="plan-preview-title">Your Lesson Plan</h2>
      <p class="plan-description">{props.plan.description}</p>
      <dl class="plan-meta">
        <dt>Background</dt><dd>{props.plan.priorKnowledge}</dd>
      </dl>
      <ol class="plan-chapters">
        <For each={props.plan.lessonPlan.chapters}>
          {(ch) => (
            <li class="plan-chapter">
              <strong>{ch.title}</strong>
              <Show when={ch.description}>
                <span>{ch.description}</span>
              </Show>
            </li>
          )}
        </For>
      </ol>
      <button class="btn-primary" onClick={props.onSave} disabled={props.saving}>
        {props.saving ? "Saving…" : "Save Book"}
      </button>
    </div>
  );
}
